module.exports = {
  "ALIVE_IMG": "https://",
  "PREFIX": ".",
  "AUTO_READ_STATUS": true,
  "MODE": "inbox",
  "BOT_NUMBER": "94769615736",
  "OMDB_API_KEY": "76cb7f39",
  "READ_CMD": true,
  "AUTO_VOICE": false,
  "AUTO_STICKER": false,
  "AUTO_REPLY": true,
  "AUTO_REACT": false,
  "WELCOME": true,
  "ANTI_BAD": false,
  "ANTI_BOT": true,
  "ANTI_LINK": true,
  "ANTI_CALL": false,
  "ANTI_DELETE": false,
  "ALLWAYS_ONLINE": true,
  "MOROCCO_BLOCK": true,
  "BTN_MSG": false,
  "OWNER_NAME": "MR Dakshina",
  "NEWS_JID": "1234567890@s.whatsapp.net",
  "AUTO_TYPING": false,
  "AUTO_RECORDING": true,
  "AUTO_NEWS": true,
  "OWNER_REACT": false,
  "EMOJI": "🏷"
};
